### ISSUE TITLE
Your generator is broken

### ISSUE THREAD

**Issue by SBoudrias** [notorii/generator-mean-seed#19]
You're breaking your generator by defining your dependency version this way: https://github.com/notorii/generator-mean-seed/blob/master/package.json#L43-L47

The last release of yeoman-generator is not backward compatible and is breaking your generator.

**Comment by awaemmanuel** [comment]
I'm having the same issue as SBoudrias.. Below is the error I get when trying to scafold a directive.

 Run Grunt (if skipped, you will have to run yourself after Yeoman completes)? 1
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'capitalize' of undefined
    at NgDirectiveGenerator.<anonymous> (/usr/local/lib/node_modules/generator-mean-seed/ng-directive/index.js:107:80)
    at NgDirectiveGenerator.<anonymous> (/usr/local/lib/node_modules/generator-mean-seed/node_modules/yeoman-generator/lib/base.js:233:7)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1977:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1914:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:5032:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1914:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:3345:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)

**Comment by matthewbussa** [comment]
I've had the same problem and it's a show stopper. Until the author accepts the pull request, the following steps served as a workaround:
1. Uninstall the generator-mean-seed from the terminal by issuing the following command:
npm -g uninstall generator-mean-seed
2. Clone the repository locally into a directory of your choice:
git clone https://github.com/notorii/generator-mean-seed.git
3. Manually make the following changes to the package.json file.  This will fix the issue with dependency versions
https://github.com/notorii/generator-mean-seed/blob/master/package.json#L43-L47
4. Once the changes are put in place, run the link command in the generator-mean-seed directory
npm link .

Now you can run the sub-generators without error.

Happy Coding!

**Comment by awaemmanuel** [comment]
Hello thank you so much,  by link command you mean "yo mean-seed" right or do you mean a literal file linking using $ln - s

**Comment by matthewbussa** [comment]
By link command I mean the npm link command.  Run the following command in the generator-mean-seed directory:
npm link .

Once this command is ran,  you can do your normal "yo mean-seed" operations

**Comment by SBoudrias** [comment]
It's actually way easier to only install from my git fork directly: `npm -g install SBoudrias/generator-mean-seed#patch-1`
