### ISSUE TITLE
ng-derective sub generator is not working

### ISSUE THREAD

**Issue by r-porter** [notorii/generator-mean-seed#22]

**Comment by awaemmanuel** [comment]
/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'capitalize' of undefined
    at NgDirectiveGenerator.<anonymous> (/usr/local/lib/node_modules/generator-mean-seed/ng-directive/index.js:107:80)
    at NgDirectiveGenerator.<anonymous> (/usr/local/lib/node_modules/generator-mean-seed/node_modules/yeoman-generator/lib/base.js:233:7)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1977:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1914:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:5032:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1914:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:3345:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)

**Comment by lukemadera** [comment]
Thanks for the logs @awaemmanuel 
Seems like the underscore dependency was missing. I just added it and pushed an update - could you try again? And if that still does not work, try installing underscore globally and then see if it works?

**Comment by awaemmanuel** [comment]
Hello Luke,  Thanks I'll try again.

**Comment by awaemmanuel** [comment]
So do npm install - g underscore?

**Comment by awaemmanuel** [comment]
So do npm install - g underscore?

**Comment by lukemadera** [comment]
@awaemmanuel First try updating the generator and running as is (I added underscore as a dependency there). If that does not work then yes, run `npm install -g underscore`

**Comment by lukemadera** [comment]
Actually this should be fixed with https://github.com/notorii/generator-mean-seed/issues/19

**Comment by awaemmanuel** [comment]
Yea it seems as a duplicate ticket.
