### ISSUE TITLE
Cannot find module 'express'

### ISSUE THREAD

**Issue by iyangim** [notorii/generator-mean-seed#33]
I just follow the instruction. Also another project without this mean-seed works find.
But command "$ node run.js" is like this.
What is the problem?
----------------------------------------------------------------------------
K-MacBookRetina:mean-seed iyangim$ node run.js config=test
configFile: ./app/configs/config.test.json
module.js:339
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/iyangim/Documents/nodejs/mean-seed/app/server.js:17:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
K-MacBookRetina:mean-seed iyangim$

**Comment by iyangim** [comment]
I didn't install phantonJS. So install it and "bower update && bower install", it is OK!!

**Comment by amandeepmittal** [comment]
If everything is okay, can you please close this issue.
